stages:
  - build
  - test
  - deploy
  - switch
  - cleanup

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

deploy_green:
  stage: deploy
  script:
    - ./deploy.sh green

validate_green:
  stage: deploy
  script:
    - ./health_check.sh green

switch_to_green:
  stage: switch
  script:
    - ./switch_traffic.sh green

cleanup_blue:
  stage: cleanup
  script:
    - ./teardown.sh blue
